---
resources:
- name: resource-02_testing_CD-pipeline
  type: git
  source:
    uri: https://github.com/BiancaLeitner/continuous_delivery_assignments/tree/master/02_testing_CD-pipeline.git
- name: resource-app
  type: git
  source:
    uri: https://github.com/BiancaLeitner/continuous_delivery_assignments/tree/master/02_testing_CD-pipeline/blog.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: job-deploy-app
  public: true
  serial: true
  plan:
  - get: resource-02_testing_CD-pipeline
  - get: resource-app
    trigger: true
  - task: web-app-tests
    file: resource-02_testing_CD-pipeline/job_inputs/task_run_tests.yml
  - put: resource-deploy-web-app
    params:
      manifest: resource-app/manifest.yml
      path: resource-app