---
resources:
  - name: git-repository
    type: git
    source:
      uri: "https://github.com/BiancaLeitner/task_01_concourse.git"

jobs:
- name: commit-stage
  plan:
  - get: git-repository
    trigger: true
  - task: run-tests
    file: git-repository/ci/commit_build.yml
   
- name: deploy-stage
  serial: true
  plan:
  - get: git-repository
    trigger: true
    passed: [commit-stage]
  - task: deploy-heroku
    params:
      HEROKU_EMAIL: {{heroku_email}}
      HEROKU_TOKEN: {{heroku_token}}
    file: git-repository/ci/deploy_build.yml